
CREATE OR ALTER FUNCTION TELEFONE_FUNC (@TEL VARCHAR(50))

RETURNS VARCHAR(50)

AS BEGIN 
DECLARE @DDD VARCHAR(50)
DECLARE @TELEFONE VARCHAR(50) 

--SEPARA DDD COM PARENTESES
SET @telefone = ('('+(  SUBSTRING (@tel, 1,2))+') ' +   (SUBSTRING (@tel, 3,5))+ '-' + (SUBSTRING (@tel, 5,4))) 


--SET @DDD =     (SUBSTRING (@tel, 1,2) )
--SET @TELEFONE =  (SUBSTRING (@tel, 3,9))

--IF LEN (@DDD) <> 2
--BEGIN
--  SET @MSG = 'DDD INVÁLIDO'
--  RETURN @MSG
-- END

-- IF LEN (@TELEFONE) <> 9
--BEGIN
--  SET @MSG = 'TELEFONE INVÁLIDO'
--  RETURN @MSG
-- END

RETURN @TELEFONE 

END 
GO

